export const posts = [
    {
      _id: "1",
      userId: "user123",
      fullName: "John Doe",
      description: "This is a beautiful sunset.",
      address: "123 Main Street",
      picturePath: "/images/sunset.jpg",
      userPicturePath: "/images/profile/user123.jpg",
      likes: 12,
      comments: 20,
    },
    {
      _id: "2",
      userId: "user456",
      fullName: "Jane Smith",
      description: "Enjoying a delicious meal.",
      address: "456 Elm Avenue",
      picturePath: "/images/food.jpg",
      userPicturePath: "/images/profile/user456.jpg",
      likes: 8,
      comments: 15,
    },
    {
      _id: "3",
      userId: "user789",
      fullName: "David Johnson",
      description: "Exploring the great outdoors.",
      address: "789 Oak Boulevard",
      picturePath: "/images/nature.jpg",
      userPicturePath: "/images/profile/user789.jpg",
      likes: 25,
      comments: 32,
    },
    {
      _id: "4",
      userId: "user012",
      fullName: "Emily Davis",
      description: "A day at the beach.",
      address: "12 Beachfront Avenue",
      picturePath: "/images/beach.jpg",
      userPicturePath: "/images/profile/user012.jpg",
      likes: 18,
      comments: 10,
    },
    {
      _id: "5",
      userId: "user345",
      fullName: "Michael Wilson",
      description: "Celebrating a milestone.",
      address: "345 Celebration Road",
      picturePath: "/images/party.jpg",
      userPicturePath: "/images/profile/user345.jpg",
      likes: 30,
      comments: 22,
    },
  ];